// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "board01.h"

/////////////////////////////////////////////////////////////////////////////
// CBoard01

IMPLEMENT_DYNCREATE(CBoard01, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CBoard01 properties

/////////////////////////////////////////////////////////////////////////////
// CBoard01 operations
